-- Run this in the Supabase SQL Editor

-- 1. NEWS TABLE
create table if not exists news (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text not null,
  image_url text,
  is_published boolean default true
);
alter table news enable row level security;
create policy "Public can view news" on news for select using (true);
create policy "Authenticated users can manage news" on news for all using (auth.role() = 'authenticated');


-- 2. EVENTS TABLE
create table if not exists events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  date date not null,
  time text,
  description text,
  category text default 'General'
);
alter table events enable row level security;
create policy "Public can view events" on events for select using (true);
create policy "Authenticated users can manage events" on events for all using (auth.role() = 'authenticated');


-- 3. GALLERY TABLE
create table if not exists gallery (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  image_url text not null,
  caption text,
  category text default 'General'
);
alter table gallery enable row level security;
create policy "Public can view gallery" on gallery for select using (true);
create policy "Authenticated users can manage gallery" on gallery for all using (auth.role() = 'authenticated');


-- 4. MESSAGES TABLE (Contact Form)
create table if not exists messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  phone text,
  subject text,
  message text not null,
  status text default 'Unread'
);
alter table messages enable row level security;
create policy "Public can insert messages" on messages for insert with check (true);
create policy "Authenticated users can manage messages" on messages for all using (auth.role() = 'authenticated');
